name: Main

on:
  push:
    branches: [main]
  schedule:
    - cron: "0 8,20 * * *"

jobs:
  unit-tests:
    name: Unit tests
    uses: swiftlang/github-workflows/.github/workflows/swift_package_test.yml@0.0.15
    with:
      linux_swift_versions: '["nightly-main"]'
