name: PR

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  soundness:
    name: Soundness
    uses: swiftlang/github-workflows/.github/workflows/soundness.yml@main
    with:
      license_header_check_project_name: "Hummingbird server framework"


  unit-tests:
    name: Unit tests
    uses: swiftlang/github-workflows/.github/workflows/swift_package_test.yml@0.0.15
    with:
      linux_swift_versions: '["6.2", "6.3", "6.4"]'
      enable_macos_checks: true
      macos_xcode_versions: '["swift_6.3", "swift_6.4"]'

  cxx-interop:
    name: Cxx interop
    uses: apple/swift-nio/.github/workflows/cxx_interop.yml@main
